  steps:
    # Step 1: Build the Docker image
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 'gcr.io/${PROJECT_ID}/gishta-promotions-backend', '.']

    # Step 2: Push the Docker image to Google Container Registry
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/${PROJECT_ID}/gishta-promotions-backend']

    # Step 3: Retrieve secrets and set environment variables
    - name: 'gcr.io/cloud-builders/gcloud'
      id: 'retrieve-secrets'
      entrypoint: 'bash'
      args:
        - '-c'
        - |
          export OPENAI_API_KEY=$(gcloud secrets versions access latest --secret=OPENAI_API_KEY)
          echo "OPENAI_API_KEY=${OPENAI_API_KEY}" >> /workspace/.env

    # Step 4: Deploy the Docker image to Google Cloud Run
    - name: 'gcr.io/cloud-builders/gcloud'
      args: [
        'run', 'deploy', 'gishta-promotions-backend',
        '--image', 'gcr.io/${_PROJECT_ID}/gishta-promotions-backend',
        '--platform', 'managed',
        '--region', 'us-central1',
        '--allow-unauthenticated',
        '--memory', '16GiB',
        '--set-env-vars', 'PROJECT_ID=${PROJECT_ID},CONTENT_GENERATION_MODEL_NAME=${CONTENT_GENERATION_MODEL_NAME}',
      ]

  # Substitutions
  substitutions:
    PROJECT_ID: 'lyrical-medley-419209'
    CONTENT_GENERATION_MODEL_NAME: 'production'

  # Timeout for the build (optional)
  timeout: '900s'
