steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/gishta-promotions-backend', '.']

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/gishta-promotions-backend']

  # Step 3: Set up kubectl (Kubernetes command-line tool)
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials gishta-promo-cluster --zone us-central1-a
        kubectl create secret generic openai-api-key --from-literal=OPENAI_API_KEY=$(gcloud secrets versions access latest --secret=OPENAI_API_KEY)

  # Step 4: Deploy the Docker image to GKE
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['set', 'image', 'deployment/gishta-promotions-backend', 'gishta-promotions-backend=gcr.io/${PROJECT_ID}/gishta-promotions-backend']

  # Step 5: Apply the Kubernetes configurations (if not applied already)
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'deployment.yaml']
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'services.yaml']

# Substitutions
substitutions:
  PROJECT_ID: 'lyrical-medley-419209'
  CONTENT_GENERATION_MODEL_NAME: 'production'

# Timeout for the build (optional)
timeout: '900s'
